# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NodeConnector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13NodeConnector.proto\"\x1f\n\x0cGreetRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\" \n\rGreetResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t29\n\rNodeConnector\x12(\n\x05Greet\x12\r.GreetRequest\x1a\x0e.GreetResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NodeConnector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETREQUEST._serialized_start=23
  _GREETREQUEST._serialized_end=54
  _GREETRESPONSE._serialized_start=56
  _GREETRESPONSE._serialized_end=88
  _NODECONNECTOR._serialized_start=90
  _NODECONNECTOR._serialized_end=147
# @@protoc_insertion_point(module_scope)
