# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NodeRPCService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14NodeRPCService.proto\"\x1f\n\x0cGreetRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\" \n\rGreetResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"7\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nnode_nodes\x18\x02 \x03(\t\"R\n\x0bTransaction\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\"l\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x12\x11\n\tprev_hash\x18\x03 \x01(\t\x12\x12\n\nblock_hash\x18\x04 \x01(\t\x12\x1a\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x0c.Transaction\"$\n\nBlockchain\x12\x16\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x06.Block\"\x07\n\x05\x45mpty2\xd8\x01\n\x0eNodeRPCService\x12(\n\x05Greet\x12\r.GreetRequest\x1a\x0e.GreetResponse\"\x00\x12(\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x06.Empty\"\x00\x12)\n\x0fSendTransaction\x12\x0c.Transaction\x1a\x06.Empty\"\x00\x12\x1d\n\tSendBlock\x12\x06.Block\x1a\x06.Empty\"\x00\x12(\n\x0fQueryBlockchain\x12\x06.Empty\x1a\x0b.Blockchain\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NodeRPCService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETREQUEST._serialized_start=24
  _GREETREQUEST._serialized_end=55
  _GREETRESPONSE._serialized_start=57
  _GREETRESPONSE._serialized_end=89
  _HEARTBEATREQUEST._serialized_start=91
  _HEARTBEATREQUEST._serialized_end=146
  _TRANSACTION._serialized_start=148
  _TRANSACTION._serialized_end=230
  _BLOCK._serialized_start=232
  _BLOCK._serialized_end=340
  _BLOCKCHAIN._serialized_start=342
  _BLOCKCHAIN._serialized_end=378
  _EMPTY._serialized_start=380
  _EMPTY._serialized_end=387
  _NODERPCSERVICE._serialized_start=390
  _NODERPCSERVICE._serialized_end=606
# @@protoc_insertion_point(module_scope)
