# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import NodeRPCService_pb2 as NodeRPCService__pb2


class NodeRPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greet = channel.unary_unary(
                '/NodeRPCService/Greet',
                request_serializer=NodeRPCService__pb2.GreetRequest.SerializeToString,
                response_deserializer=NodeRPCService__pb2.GreetResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/NodeRPCService/Heartbeat',
                request_serializer=NodeRPCService__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=NodeRPCService__pb2.Empty.FromString,
                )
        self.SendTransaction = channel.unary_unary(
                '/NodeRPCService/SendTransaction',
                request_serializer=NodeRPCService__pb2.Transaction.SerializeToString,
                response_deserializer=NodeRPCService__pb2.Empty.FromString,
                )
        self.SendBlock = channel.unary_unary(
                '/NodeRPCService/SendBlock',
                request_serializer=NodeRPCService__pb2.Block.SerializeToString,
                response_deserializer=NodeRPCService__pb2.Empty.FromString,
                )


class NodeRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Greet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greet': grpc.unary_unary_rpc_method_handler(
                    servicer.Greet,
                    request_deserializer=NodeRPCService__pb2.GreetRequest.FromString,
                    response_serializer=NodeRPCService__pb2.GreetResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=NodeRPCService__pb2.HeartbeatRequest.FromString,
                    response_serializer=NodeRPCService__pb2.Empty.SerializeToString,
            ),
            'SendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTransaction,
                    request_deserializer=NodeRPCService__pb2.Transaction.FromString,
                    response_serializer=NodeRPCService__pb2.Empty.SerializeToString,
            ),
            'SendBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBlock,
                    request_deserializer=NodeRPCService__pb2.Block.FromString,
                    response_serializer=NodeRPCService__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NodeRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeRPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Greet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeRPCService/Greet',
            NodeRPCService__pb2.GreetRequest.SerializeToString,
            NodeRPCService__pb2.GreetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeRPCService/Heartbeat',
            NodeRPCService__pb2.HeartbeatRequest.SerializeToString,
            NodeRPCService__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeRPCService/SendTransaction',
            NodeRPCService__pb2.Transaction.SerializeToString,
            NodeRPCService__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeRPCService/SendBlock',
            NodeRPCService__pb2.Block.SerializeToString,
            NodeRPCService__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
